import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        // Luxury Color Palette
        gold: {
          50: "hsl(45, 80%, 95%)",
          100: "hsl(45, 75%, 85%)",
          200: "hsl(45, 70%, 75%)",
          300: "hsl(45, 70%, 65%)",
          400: "hsl(45, 70%, 55%)",
          500: "hsl(35, 65%, 45%)",
          600: "hsl(35, 60%, 35%)",
          700: "hsl(35, 55%, 25%)",
          800: "hsl(35, 50%, 15%)",
          900: "hsl(35, 45%, 8%)",
        },
        "rose-gold": {
          50: "hsl(15, 60%, 92%)",
          100: "hsl(15, 60%, 85%)",
          200: "hsl(15, 60%, 78%)",
          300: "hsl(15, 60%, 70%)",
          400: "hsl(15, 60%, 62%)",
          500: "hsl(15, 60%, 55%)",
          600: "hsl(15, 55%, 45%)",
          700: "hsl(15, 50%, 35%)",
          800: "hsl(15, 45%, 25%)",
          900: "hsl(15, 40%, 15%)",
        },
        platinum: {
          50: "hsl(210, 15%, 95%)",
          100: "hsl(210, 15%, 88%)",
          200: "hsl(210, 15%, 80%)",
          300: "hsl(210, 15%, 72%)",
          400: "hsl(210, 15%, 65%)",
          500: "hsl(210, 15%, 58%)",
          600: "hsl(210, 15%, 50%)",
          700: "hsl(210, 15%, 42%)",
          800: "hsl(210, 15%, 34%)",
          900: "hsl(210, 15%, 26%)",
        },
        warm: {
          50: "hsl(30, 15%, 96%)",
          100: "hsl(30, 12%, 90%)",
          200: "hsl(30, 10%, 82%)",
          300: "hsl(30, 8%, 74%)",
          400: "hsl(30, 8%, 66%)",
          500: "hsl(30, 8%, 58%)",
          600: "hsl(30, 8%, 50%)",
          700: "hsl(30, 8%, 42%)",
          800: "hsl(30, 8%, 34%)",
          900: "hsl(30, 8%, 20%)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.75rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.16' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
        '7xl': ['4.5rem', { lineHeight: '1.05' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
        'display-sm': ['2.5rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'display-md': ['3.5rem', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'display-lg': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'display-xl': ['6rem', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
      },
      backdropBlur: {
        'xs': '2px',
        '3xl': '64px',
      },
      backgroundImage: {
        'luxury-gradient': 'var(--gold-gradient)',
        'surface-gradient': 'var(--surface-gradient)',
        'glass-gradient': 'var(--glass-gradient)',
        'marble-gradient': 'var(--marble-gradient)',
        'velvet-gradient': 'var(--velvet-gradient)',
        'noise': "url('data:image/svg+xml,%3Csvg width='200' height='200' viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)' opacity='0.02'/%3E%3C/svg%3E')",
      },
      boxShadow: {
        'elegant': 'var(--elegant-shadow)',
        'elegant-lg': 'var(--elegant-shadow-lg)',
        'elegant-xl': 'var(--elegant-shadow-xl)',
        'luxury-glow': 'var(--luxury-glow)',
        'inner-subtle': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
        'inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.15)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
